services:
  # mysql 컨테이너 설정
  mysql:
    image: ${DEV_MYSQL_DOCKER_HUB_ID}/mysql-dev:latest  # Docker Hub에 있는 이미지 가져오기
    container_name: mysql-dev                           # 컨테이너 이름 지정
    restart: always                                     # 서버 재시작 시 항상 같이 재시작
    ports:
      - "3306:3306"                                     # 포트 바인딩
    volumes:
      - ./mysql/data:/var/lib/mysql                     # 도커 볼륨 지정
    environment:
      # 1. Spring Boot가 연결할 데이터베이스 이름 자동 생성
      - MYSQL_DATABASE=${DEV_DB_NAME}
      # 2. Spring Boot가 접속할 때 사용할 일반 계정 자동 생성
      - MYSQL_USER=${DEV_DB_USER}
      # 3. 위 일반 계정의 비밀번호 설정
      - MYSQL_PASSWORD=${DEV_DB_PW}
      # 4. MySQL 관리자(root) 계정의 비밀번호 설정
      - MYSQL_ROOT_PASSWORD=${DEV_DB_ROOT_PW}
        # -> 이 환경변수들은 최초 1회만 동작한다.